# Aether runtime configuration

[database]
type = "POSTGRESQL"
name = "url-shortener"
host = "localhost"
port = 5432
database = "forge"
username = "forge"
password = "forge"

[database.pool_config]
min_connections = 4
max_connections = 20
idle_timeout = "10m"
connection_timeout = "5s"
max_lifetime = "30m"
leak_detection_timeout = "0s"
