# Forge cluster configuration

[cluster]
nodes = 5
management_port = 5150
dashboard_port = 8888
app_http_port = 8070
auto_heal_enabled = false

[database]
enabled = true
port = 9092
name = "forge"
persistent = false
init_script = "./schema/url-shortener.sql"
